title: My Webpage
author: Roshan
email: roshan_shaju@infosys.com
description: > # this means to ignore newlines until "baseurl:"
This is my webpage

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
